# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: iSponsorBlockTV add-on
version: "1.0.2"
slug: isponsorblocktv
description: Skip sponsor segments in YouTube videos playing on an Apple TV.
url: "https://github.com/bertybuttface/addons/tree/main/isponsorblocktv"
arch:
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  apikey: null # get youtube apikey: https://developers.google.com/youtube/registering_an_application
  atvs:
    - name: null
      identifier: null
      airplay_credentials: null
  channel_whitelist: []
  skip_categories:
    - "sponsor"
schema:
  apikey: "str"
  atvs:
    - name: "str?"
      identifier: "str"
      airplay_credentials: "str"
  channel_whitelist:
    - id: "str"
    - name: "str"
  skip_categories:
    - match(^.*(sponsor|selfpromo|exclusive_access|interaction|poi_highlight|intro|outro|preview|filler|music_offtopic).*$)
image: "ghcr.io/bertybuttface/{arch}-addon-isponsorblocktv"
host_network: true
