# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.18"
  amd64: "ghcr.io/home-assistant/amd64-base:3.18"
labels:
  org.opencontainers.image.title: "Dendrite"
  org.opencontainers.image.description: "Next-generation Matrix homeserver written in Go"
  org.opencontainers.image.source: "https://github.com/matrix-org/dendrite"
  org.opencontainers.image.licenses: "Apache-2.0"
  org.opencontainers.image.documentation: "https://matrix-org.github.io/dendrite/"
  org.opencontainers.image.vendor: "The Matrix.org Foundation C.I.C."
args:
  TEMPIO_VERSION: "2021.09.0"
