# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Matrix NG"
version: "0.0.9"
slug: "matrix_ng"
description: >-
  This add-on provides a Matrix server (either Dendrite or Conduit), a frontend (Element)
  and includes mau-bridges to connect to external services
url: "https://github.com/bertybuttface/addons/tree/main/matrix-ng"
arch:
  - "aarch64"
  - "amd64"
ingress: true
init: false
map:
  - share:rw
  - ssl
ports:
  8099/tcp: 8099 # element
  8008/tcp: 8008 # matrix
  8448/tcp: 8448 # matrix
  8080/tcp: 8080 # manhole
options:
  manhole: false
  server_name: "matrix.example.org"
  disable_federation: false
  hs_url: "https://localhost:8448"
  is_url: "https://vector.im"
  # registration_shared_secret: "your randomly generated long secret"
  private_key: "/ssl/privkey.pem"
  public_key: "/ssl/fullchain.pem"
  maubridges:
    - "discord"
    - "whatsapp"
  maupybridges:
    - "telegram"
  telegram:
    api_id: ""
    api_hash: ""
  postgres_max_connections: 400

schema:
  manhole: bool
  server_name: str
  disable_federation: bool
  hs_url: str
  is_url: str
  # registration_shared_secret: str
  private_key: str
  public_key: str
  maubridges: # discord|gmessages|signalgo|slack|whatsapp
    - match(^.*(discord|whatsapp).*$)
  maupybridges: # telegram
    - match(^.*(telegram).*$)
  telegram:
    api_id: str?
    api_hash: str?
  postgres_max_connections: int
stage: "experimental"
image: "ghcr.io/bertybuttface/{arch}-addon-matrix-ng"
host_network: true
