---
name: ziti-tunneller
version: 1.0.5
slug: zititunneller
description: Tunnels the homeassistant dashboard into your openziti zero trust network.
url: https://github.com/bertybuttface/addons/zititunneller
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  log_level: info
  jwt: ""
schema:
  log_level: list(error|warning|info|debug)
  jwt: str?
image: "ghcr.io/bertybuttface/{arch}-addon-zititunneller"
